spring:
  application:
    name: perfume-shop
  datasource:
    url: jdbc:postgresql://localhost:5432/perfume_shop
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

jwt:
  secret: ${JWT_SECRET:your-secret-key-must-be-at-least-32-characters}
  expiration: 86400000 # 24 hours in milliseconds